"""Initial schema — all six objects

Revision ID: a72a279e0184
Revises:
Create Date: 2026-06-11 02:13:28.927708

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a72a279e0184'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_rates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('persona_tier', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('n_sample', sa.Integer(), nullable=False),
    sa.Column('actual_rate', sa.Float(), nullable=True),
    sa.Column('benchmark_rate', sa.Float(), nullable=False),
    sa.Column('k_strength', sa.Integer(), nullable=False),
    sa.Column('blended_rate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('baseline_90d', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('persona_tier', sa.String(length=30), nullable=True),
    sa.Column('points_value', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('account_ref', sa.String(length=255), nullable=False),
    sa.Column('contact_ref', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('reverses_event_id', sa.String(length=36), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_ref', 'event_log', ['account_ref'], unique=False)
    op.create_index('ix_event_type_occurred', 'event_log', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_job_id', 'event_log', ['job_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('parent_goal_id', sa.String(length=36), nullable=True),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('funnel_stage', sa.String(length=20), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('trigger', sqlite.JSON(), nullable=True),
    sa.Column('account_ref', sa.String(length=255), nullable=True),
    sa.Column('contact_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('input_payload', sqlite.JSON(), nullable=True),
    sa.Column('output', sqlite.JSON(), nullable=True),
    sa.Column('policy_flags', sqlite.JSON(), nullable=True),
    sa.Column('approval', sqlite.JSON(), nullable=True),
    sa.Column('write_back_ref', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('counts', sqlite.JSON(), nullable=True),
    sa.Column('points', sqlite.JSON(), nullable=True),
    sa.Column('persona_mix', sqlite.JSON(), nullable=True),
    sa.Column('pct_goal', sa.Float(), nullable=False),
    sa.Column('pct_period_elapsed', sa.Float(), nullable=False),
    sa.Column('pace_gap', sa.Float(), nullable=False),
    sa.Column('gap_by_stage', sqlite.JSON(), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('weekly_bookings_required', sa.Float(), nullable=False),
    sa.Column('weekly_held_target', sa.Float(), nullable=False),
    sa.Column('daily_allocation', sqlite.JSON(), nullable=True),
    sa.Column('rates_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('capacity', sqlite.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('replan_reason', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    op.drop_table('funnel_state')
    op.drop_table('jobs')
    op.drop_table('goals')
    op.drop_index('ix_job_id', table_name='event_log')
    op.drop_index('ix_event_type_occurred', table_name='event_log')
    op.drop_index('ix_account_ref', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('conversion_rates')
    # ### end Alembic commands ###
